# Generated by Django 4.0.5 on 2022-06-20 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='date_expired',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='history',
            name='date_returned',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
